### ISSUE TITLE
Can Risam achieve batch estimation

### ISSUE THREAD

**Issue by qian5683** [rpl-cmu/risam#3]
Thank you for your surprising work!!! I checked the example code and it seems that there is only incremental estimation. Can Risam achieve batch estimation? If possible, what should I do? Thank you very much

**Comment by DanMcGann** [comment]
Thanks for you question!

riSAM is explicitly an incremental solver being derived from the iSAM2 incremental algorithm. To perform batch solving with Graduated Non-Convexity you can use the original batch GNC solver (proposed here: https://arxiv.org/pdf/1909.08605.pdf) provided in GTSAM (Documentation here: https://gtsam.org/doxygen/a04308.html)
